kind: ClusterIssuer
apiVersion: certmanager.k8s.io/v1alpha1
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ashton@ashtonc.ca
    privateKeySecretRef:
      name: letsencrypt-production
    dns01:
      providers:
      - name: clouddns
        clouddns:
          project: ashtonc-home
          serviceAccountSecretRef:
            name: clouddns-service-account
            key: gce-service-account-key.json

