FROM nginx:stable-alpine

ADD https://storage.googleapis.com/ashtonc.ca/deploy/gcs_proxy.conf /etc/nginx/conf.d/gcs_proxy.conf
ADD https://storage.googleapis.com/ashtonc.ca/deploy/proxy_params /etc/nginx/proxy_params

