apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ashtonc-home
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: ashtonc-home
    spec:
      containers:
      - name: ashtonc-home
        image: nginx:alpine
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - "wget https://raw.githubusercontent.com/zzh8829/zihao/master/deploy/nginx_gcs_proxy.conf -O /etc/nginx/nginx_gcs_proxy.conf && \
            wget https://raw.githubusercontent.com/zzh8829/zihao/master/deploy/nginx_zihao.conf -O /etc/nginx/conf.d/default.conf && \
            nginx -g 'daemon off;'"
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "30Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: ashtonc-home
  labels:
    app: ashtonc-home
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: ashtonc-home
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ashtonc-home
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - ashtonc.ca
    - www.ashtonc.ca
    secretName: ashtonc-home-tls
  rules:
  - host: ashtonc.ca
    http:
      paths:
      - backend:
          serviceName: ashtonc-home
          servicePort: 80
        path: /
  - host: www.ashtonc.ca
    http:
      paths:
      - backend:
          serviceName: ashtonc-home
          servicePort: 80
        path: /

