kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ashtonc-home
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: ashtonc-home
    spec:
      containers:
      - name: ashtonc-home
        image: gcr.io/ashtonc-home/ashtonc-home:master
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

